services:
  traefik:
    volumes:
      - ${ROOT_DIR}/traefik/static/traefik.prod.yml:/etc/traefik/traefik.yml:ro
      - traefik-acme:/letsencrypt
    restart: unless-stopped

volumes:
  traefik-acme:
