services:
  traefik:
    image: traefik:v3.6
    container_name: traefik
    command:
      - "--configfile=/etc/traefik/traefik.yml"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      authentik-server:
        condition: service_healthy
      authentik-worker:
        condition: service_healthy
    volumes:
      - ./traefik/dynamic:/etc/traefik/dynamic
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
