
  services:

    typst-worker:
      build:
        context: worker
        dockerfile: Dockerfle.typst

    latex-worker:
      build:
        context: worker
        dockerfile: Dockerfle.latex

    restapi:
      build:
        context: restapi
        dockerfile: Dockerfle
