services:

  redis:
    image: redis:8.8-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
  
  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    restart: unless-stopped
    ports:
      - "5540:5540"
    volumes:
      - redisinsight-data:/data
    environment:
      REDISINSIGHT_ACCEPT_LICENSE: true
      RI_APP_HOST: 0.0.0.0
    depends_on:
      - redis

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" # API port
      - "9001:9001" # Console port
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 3

  minio-init:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb set myminio/rendered-documents --ignore-existing;
      # /usr/bin/mc anonymous set download myminio/rendered-documents;
      exit 0;
      "

  restapi:
    build:
      context: ./goworkspace
      dockerfile: Dockerfile.restapi
    container_name: restapi
    ports: 
      - "8080:8080"
    env_file:
      - ./goworkspace/restapi.env
      - ./goworkspace/storage.env
    volumes: #ONLY FOR DEV
      - /home/wojte/MyDevEnv/tex-typst-rendering-cluster/goworkspace/restapi/static:/app/static
    depends_on:
      - redis
      - minio
    restart: unless-stopped


  worker-typst:
    build:
      context: ./goworkspace
      dockerfile: Dockerfile.worker-typst
    container_name: worker-typst
    env_file:
      - ./goworkspace/worker.env
      - ./goworkspace/worker-typst.env
      - ./goworkspace/storage.env
    depends_on:
      - redis
      - minio
    restart: unless-stopped

  worker-latex:
    build:
      context: ./goworkspace
      dockerfile: Dockerfile.worker-latex
    container_name: worker-latex
    env_file:
      - ./goworkspace/worker.env
      - ./goworkspace/worker-latex.env
      - ./goworkspace/storage.env
    depends_on:
      - redis
      - minio
    restart: unless-stopped
    

  # ================================== monitoring/observability

  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: redis-exporter
    environment:
      REDIS_ADDR: redis://redis:6379
      REDIS_EXPORTER_CHECK_STREAMS: stream:latex,stream:typst
    depends_on:
      - redis
    restart: unless-stopped

  cadvisor: 
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: cadvisor
    privileged: true
    # devices:
    #   - /dev/kmsg:/dev/kmsg
    ports: 
      - "8081:8080"
    volumes: 
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    # command:
    #   - "--docker_only=true"
    #   - "--store_container_labels=false"
    #   - "--disable_root_cgroup_stats=true"
    #   - "--disable_metrics=advtcp,cpuLoad,hugetlb,memory_numa,percpu,process,referenced_memory,resctrl,sched,tcp,udp"
    restart: unless-stopped


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports: 
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  minio_data:
  grafana_data:
  prometheus_data:
  redisinsight-data: