services:
  minio:
    image: pgsty/silo:RELEASE.2026-09-16T00-00-00Z
    container_name: minio
    command: server /data --console-address ":9001" --address=":9002"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minio.rule=Host(`${GLOBAL_APP_DOMAIN}`) && PathPrefix(`/${MINIO_BUCKET_NAME}/`)"
      - "traefik.http.routers.minio.entrypoints=websecure"
      - "traefik.http.routers.minio.tls=true"
      - "traefik.http.routers.minio.tls.certresolver=le"
      - "traefik.http.routers.minio.priority=13"
      - "traefik.http.services.minio.loadbalancer.server.port=9002"
      - "traefik.http.routers.minio.middlewares=authentik-auth"

    # ports:
    #   - "9000:9000" # API port
      # - "9001:9001" # Console port
    environment:
      - MINIO_EXTERNAL_ENDPOINT=${MINIO_EXTERNAL_ENDPOINT}
      - MINIO_INTERNAL_ENDPOINT=${MINIO_INTERNAL_ENDPOINT}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_USE_SSL=${MINIO_USE_SSL}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
    volumes:
      - minio_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:9002/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 3



  minio-init:
    image: pgsty/mc:RELEASE.2026-09-16T00-00-00Z
    depends_on:
      - minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc alias set myminio http://minio:9002 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD};
      /usr/bin/mc mb myminio/$${MINIO_BUCKET_NAME} --ignore-existing;
      # /usr/bin/mc anonymous set download myminio/$${MINIO_BUCKET_NAME};
      exit 0;
      "
