global:
    scrape_interval: 15s

scrape_configs:
  # - job_name: restapi
  #   static_configs:
  #     - targets: ["restapi:8080"]

  # - job_name: worker-latex
  #   static_configs:
  #     - targets: ["worker-latex:9100"]

  # - job_name: worker-typst
  #   static_configs:
  #     - targets: ["restapi:9100"]

  - job_name: redis
    static_configs:
      - targets: ["redis-exporter:9121"]

  - job_name: cadvisor
    static_configs:
      - targets: ["cadvisor:8080"]

  # - job_name: minio
  #   metrics_path: /minio/v2/metrics/cluster
  #   bearer_token: "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9tZXRoZXVzIiwic3ViIjoiUTNBTTNVUTg2N1NQUVFBNDNQMkYiLCJleHAiOjQ5MzUyMjQzMzR9.LmTXjxudb6ls7-wT5VBpxl-RkhsT7SE7vSspb8CzFaw4fFUuZLE6efybfqw5Qv4gpuKs-uKB1-46ww1lZPs_BA"
  #   static_configs:
  #     - targets: ["minio:9000"]

  - job_name: minio
    bearer_token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9tZXRoZXVzIiwic3ViIjoibWluaW9hZG1pbiIsImV4cCI6NDkzNTIzMTU3OH0.wnzsDmSyXkJkOn4-R98eOhzamUnZDBTeYtQhaCX19sLaW8NzOpMLIpNCgndGki4zkHcca1h-7e7Sjd-Lw6SLsQ
    metrics_path: /minio/v2/metrics/cluster
    scheme: http
    static_configs:
    - targets: ['minio:9000']
