{
 "title": "Redis Stream Exporter",
 "description": "Exports Redis Stream metrics for Prometheus monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(redis_stream_length, job)"
    }
   },
   {
    "name": "redis_server",
    "query": {
     "query": "label_values(redis_stream_length{job=~\"$job\"}, redis_server)"
    }
   },
   {
    "name": "stream",
    "query": {
     "query": "label_values(redis_stream_length{job=~\"$job\", redis_server=~\"$redis_server\"}, stream)"
    }
   },
   {
    "name": "group",
    "query": {
     "query": "label_values(redis_stream_consumer_group_consumers_total{job=~\"$job\", redis_server=~\"$redis_server\", stream=~\"$stream\"}, group)"
    }
   },
   {
    "name": "consumer",
    "query": {
     "query": "label_values(redis_stream_consumer_idle_time_seconds_total{job=~\"$job\", redis_server=~\"$redis_server\", stream=~\"$stream\", group=~\"$group\"}, consumer)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Stream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Stream Length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "redis_stream_length{job=~\"$job\", redis_server=~\"$redis_server\", stream=~\"$stream\"}",
     "legendFormat": "{{stream}} - {{redis_server}}"
    }
   ]
  },
  {
   "title": "Stream Consumers Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "redis_stream_consumers_total{job=~\"$job\", redis_server=~\"$redis_server\", stream=~\"$stream\"}",
     "legendFormat": "{{stream}} - {{redis_server}}"
    }
   ]
  },
  { "title": "Consumer Group", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Consumer Group Pending Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "redis_stream_consumer_group_pending_messages_total{job=~\"$job\", redis_server=~\"$redis_server\", group=~\"$group\"}",
     "legendFormat": "{{stream}} - {{redis_server}} - {{group}}"
    }
   ]
  },
  {
   "title": "Consumer Group Consumers Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "redis_stream_consumer_group_consumers_total{job=~\"$job\", redis_server=~\"$redis_server\", group=~\"$group\"}",
     "legendFormat": "{{stream}} - {{redis_server}} - {{group}}"
    }
   ]
  },
  { "title": "Consumer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Consumer Time Idle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(redis_stream_consumer_idle_time_seconds_total{job=~\"$job\", redis_server=~\"$redis_server\", group=~\"$group\", consumer=~\"$consumer\"}[1m])",
     "legendFormat": "{{stream}} - {{redis_server}} - {{group}} - {{consumer}}"
    }
   ]
  }
 ]
}