
// Macros/Commands
#let PGLnk = $"PGL"_(n,k)$
#let PGL(n,k) = $"PGL"_(#n,#k)$
#let PGLover(n,k) = $"PGL"_(#n)(#k)$
#let PGL1(n) = $"PGL"_(#n)$
#let GLnk = $"GL"_(n,k)$
#let GLn = $"GL"_n$
#let SLnk = $"SL"_(n,k)$
#let SL1(n) = $"SL"_#n$
#let SL2(n,k) = $"SL"_(#n,#k)$
#let Mnnk = $"M"_(n,n)(k)$
#let Mnnk2(n,k) = $"M"_(#n,#n)(#k)$
#let AY = $A(Y)$
#let Pnk(n,k) = $PP^(#n)_(#k)$
#let Ank(n,k) = $AA^(#n)_(#k)$
#let Aut = "Aut"
#let GLover(n,k) = $"GL"_(#n)(#k)$
#let ideal = $lt.tri.eq$
#let Gmk = $GG_(m,k)$
#let Affnk = $"Aff"(Ank(n,k))$
#let Affnk2(n,k) = $"Aff"(Ank(#n,#k))$
#let Im(body) = $"Im"thin #body$
#let TODO = text("TODO", stroke: red)
#let IFF = $arrow.r.l.double.long$
#let implies = $arrow.r.double.long$
#let RED(body) = text([#body], fill: red, weight: "bold")


// ================================================
// ================================================
// ================================================
// ================================================


= Exercise 27

Recall that $k=overline(k), $ $R=k[y_1,y_2, dots, y_n]$, $S=k[X_0,X_1,dots,X_n]$, $R_d = {f in R : deg f = d}$  (with $deg$ being the total degree), and
$hom_0 (f in R_d) = X_0^d f(X_1/X_0, X_2/X_0, dots, X_n/X_0)  in S_d$.

Consider $hom_0:R arrow S$.

+ Give an example to show that $hom_0(f+g) != hom_0(f) + hom_0(g)$.

+ Use (1) to construct an ideal $I=(f_1,dots, f_r) lt.tri.eq R$ such that $hom_0(I) = ({hom_0(f): f in I})$ is #underline[not] generated by polynomials $hom_0(f_1), dots, hom_0(f_r)$.   


== Solution of (1)
Take $f = 1+ y_1$ and $g=y_1^2$. Then 
$ 
  hom_0(1+ y_1 + y_1^2 in R_2) 
  =  X_0^2 + X_1X_0 + X_1^2 \ 
  != X_0 + X_1 + X_1^2 
  = hom_0(1+ y_1 in R_1) + hom_0(y_1^2 in R_2). 
$

== Solution of (2)
Consider an ideal $I = (f,g) = (1+ y_1, y_1^2) ideal R$ and observe that $y_1(y_1 +1) + (-1) y_1^2 = y_1 in I$. Hence, $hom_0(y_1) = X_1 in hom_0(I)$. 
Suppose that there exist $A,B in S$ such that $X_1 = A(X_0+X_1) + B X_1^2$. Define a $k$-algebra homomorphism
$ 
phi : k[X_0,X_1] slash (X_0 + X_1) arrow.long k[X_1],
wide X_0 mapsto - X_1, 
quad X_1 mapsto X_1.  
$ 
Then 
$ X_1 = phi (X_1) =  phi(A(X_0+X_1)) + phi(B X_1^2) =  phi(B) X_1^2, quad "where" phi(B) in k[X_1]. $
But $deg (X_1) < deg (phi(B) X_1^2)$, a contradiction. Thus, 
$ hom_0(I) eq.not (hom_0(f), hom_0(g)), $ 
 because  $X_1 in.not  (X_0+X_1, X_1^2)$.


= Exercise 28
Recall that for an affine variety $Y$ the coordinate ring $AY$ is an intrinsic object (cf. _Thm 4.4_). There's #underline[no] analogous result for projective varieties. Indeed, if $Y subset.eq Pnk(n,k)$ is isomorphic to $Z subset.eq  Pnk(n,k)$, then it's #underline[not] true in general that 
$ k[x_0,dots,x_n] slash J(Y) tilde.equiv k[x_0,dots,x_n] slash J(Z)  $

#underline[Give] an explicit example to show this (cf. _Ex. 30_). 


== Solution

Defines sets 
$
X = {[x:y:z] in Pnk(2,k): z = 0} = Z(z), \
Y = {[x:y:z] in Pnk(2,k): x^2 + y^2 = z^2} = Z(x^2 + y^2 - z^2).
$
Clearly, $X tilde.equiv Pnk(1,k)$ as $X$ is just a projective line. From the last lecture, we know that $Y tilde.equiv Pnk(1,k)$ as well. 
// Denote $R := k[x,y,z]$. Their defining ideals are 
Since, $z$ and $x^2 + y^2 - z^2$ are irreducible polynomials in $k[x,y,z]$, the ideals generated by them are prime. In _Exercise 30_ we prove that prime ideals are radical and in _Exercise 32_ we prove the projective version of Hilbert's Nullstellensatz. Together they imply that
$
  J(X)  = J(Z(z)) = sqrt((z)) = (z), \
  J(Y) = J(Z(x^2 + y^2 - z^2)) = sqrt((x^2 + y^2 - z^2))  = (x^2 + y^2 - z^2),
$
hence
$
  A(X) = k[x,y,z] slash (z) tilde.equiv k[x,y], wide   
  A(Y) = k[x,y,z] slash (x^2 + y^2 - z^2).
$
However, these rings are not isomorphic as $A(X)$ is a UFD while $A(Y)$ is not. Indeed,
$
  x^2  = x x = z^2 -  y^2 = (z+y)(z-y),
$
where $x, z+y, z-y$ are irreducible in $A(Y)$ and 
$
  x!= lambda_1 (z+y), wide x!= lambda_2 (z-y), wide (z-y)!= lambda_3 (z+y),
$
for any $lambda_1,lambda_2,lambda_3 in k^times$.
Therefore, $X tilde.equiv Y$ but $A(X) tilde.equiv.not A(Y)$.


// ============================================================
// ============================================================
// ============================================================



= Exercise 29

+ For $v= (v_1, dots, v_n) in k^n$ let $t_v : Ank(n,k) arrow Ank(n,k)$ be the translation by $v$. Identify $Ank(n,k) tilde.equiv U_0 subset.eq Pnk(n,k)$ and show that $t_v$ extends to an action on $Pnk(n,k)$ and give the extended automorphism as an element of $PGLover(n+1,k)$.

+ An automorphism $phi in Aut(Ank(n,k))$ is called an affine transformation if $phi$ can be written as a linear automorphism of $Ank(n,k)$ (given by an element of $GLn$) followed by a translation.

  #underline[Show] that affine transformation form a subgroup $"Aff"(Ank(n,k)) subset.eq Aut(Ank(n,k))$ and that $"Aff"(Ank(n,k))$ is the semidirect product $k^n times.r GLover(n,k)$

+ #underline[Show] that any affine transformation extends to an automorphism of $Pnk(n,k)$. Can you see how this realizes $k^n times.r GLover(n,k)$ as a subgroup of $PGLover(n+1,k)$?

+ For $f in k[x]$ #underline[show] that $(a,b) arrow.bar (a + f(b),b)$ is an automorphism of $Ank(2,k)$. Under what conditions on $f$ it is an affine transformation? 

== Solution of (1)


#let projtranslmat = $   mat(augment: #(hline: 1, vline: 1), 
1,0, 0,   dots.c, 0 ;
v_1,1, 0, dots.c, 0;
v_2, 0, 1, dots.c, 0 ;
dots.v,dots.v, dots.v, dots.down, dots.v;
v_n,0, 0,dots.c,  1;
) $

#let projtranslmatscaled = $   mat(augment: #(hline: 1, vline: 1), 
c,0, 0,   dots.c, 0 ;
c v_1,c, 0, dots.c, 0;
c v_2, 0, c, dots.c, 0 ;
dots.v,dots.v, dots.v, dots.down, dots.v;
c v_n,0, 0,dots.c,  c;
) $



Recall that $U_0 = {[X_0,X_1,dots,X_n] in Pnk(n,k) : X_0 != 0}$

Let $phi : Ank(n,k) arrow U_0$ be an isomorphism such that, for $x_0,x_1, dots, x_n in k$,
$ 
phi ((x_1,x_2,dots,x_n)) = [1:x_1:x_2:dots:x_n] ,
quad\ phi^(-1) ([x_0:x_1:x_2:dots:x_n]) = (x_1/x_0,x_2/x_0,dots,x_n/x_0). 
$


Define another isomorphism $T_v : U_0 arrow U_0$ such that 
$ 
T_v ([x_0:dots:x_n]) 
&= phi compose t_v compose phi^(-1) ([x_0:dots:x_n]) 
= phi compose t_v ((x_1/x_0,dots,x_n/x_0))
\ &= phi (((x_1 + v_1x_0 )/x_0,dots,(x_n + v_n x_0)/x_0)) 
= [1 : (x_1 + v_1x_0 )/x_0 : dots : (x_n + v_n x_0)/x_0] 
\ &= [x_0 : x_1 + v_1x_0 : dots : x_n + v_n x_0] 
$
We can extend $T_v$ to $tilde(T_v): Pnk(n,k) arrow Pnk(n,k)$ by defining
$ 
  tilde(T_v)([x_0:dots:x_n]) = cases(
    T_v ([x_0:dots:x_n])  quad &"if" x_0 != 0,
    [x_0:dots:x_n]        &"if" x_0 =0.
  )
$





Note that,  for $x_0=1$, the map $tilde(T_v)$ behaves just like $phi$.

We can express the action of $tilde(T_v)$ as matrix multiplication of vectors from $k^n$. Indeed, let $cal(T)_v$ be a matrix which acts on $k^n$ as follows:
$
  cal(T)_v vec(x_0,x_1,x_2, dots.v,x_n) 
  = projtranslmat vec(x_0,x_1,x_2,dots.v,x_n)
  = mat(1,0; v^T, I_n; augment: #(vline:1, hline:1) ) vec(x_0,x_1,x_2,dots.v,x_n)
  // = lr([projtranslmat]) vec(x_0,x_1,x_2,dots.v,x_n)
  = vec(x_0,x_1+v_1x_0,x_2+v_2x_0,dots.v,x_n+v_n x_0)
  // \ = [x_0 : x_1+v_1x_0 : dots : x_n+v_n x_0]
  // = tilde(T_v)([x_0 : x_1: dots : x_n]).
  .
$
Note that $det(cal(T)_v) = det(I_n) =1$ so $cal(T)_v in GLover(n+1,k)$. Furthermore, we can consider an equivalence class $[cal(T)_v]={c cal(T)_v : c in k^times } in PGLover(n+1,k)$ which acts on points from $Pnk(n,k)$. Then,  $[cal(T)_v] P = [c I cal(T)_v] P$ for every $P in Pnk(n,k)$ and $c in k^times$. It is clear that
$ [cal(T)_v] [x_0:dots:x_n] = tilde(T_v)([x_0:dots:x_n]). $


== Solution of (2)

Let $ Affnk in.rev psi_(A,v) : Ank(n,k) arrow Ank(n,k)$ be an affine transformation given by $psi_(A,v)(x in Ank(n,k)) = A x + v$ for $A in GLover(n,k)$ and a vector $v=(v_1,dots,v_n) in k^n$ (whether it is a column or a row vector should be clear from the context).

We can compose two such transformations as follows: 
$ (psi_(A_1,v_1) compose psi_(A_2,v_2))(x) = A_1(A_2 x + v_2) + v_1 = (A_1A_2) x + (A_1v_2 + v_1), $
hence $psi_(A_1,v_1) compose psi_(A_2,v_2) in Affnk$.
We can express the same composition rule using a different notation:
$ (A_1, v_1) dot (A_2, v_2) = (A_1A_2, A_1v_2 + v_1). $

Next, we check that $Affnk$ is a subgroup of $Aut(Ank(n,k))$:
$ id (x) = I_n x + 0 = x quad arrow.long.double quad  id = (I_n, 0), $

$ 
  (A,v) dot (A^(-1), -A^(-1)v) = (A A^(-1), -A A^(-1) v + v) = (I_n, 0), \
  (A^(-1), -A^(-1)v) dot (A,v) = (I_n, A^(-1)v - A^(-1)v) =  (I_n, 0),
$

$
((A,a) dot (B,b)) dot (C,c) = (A B, A b + a) dot (C,c) = (A B C, A B c + A b + a), \
(A,a) dot ((B,b) dot (C,c)) = (A,a) dot (B C, B c + b) = (A B C, A B c + A b + a).
$
Therefore, $Affnk$ is a subgroup of $Aut(Ank(n,k))$.

Define the sets of translations and linear automorphisms of $Ank(n,k)$:
$ 
  T = {(I_n, v) : v in k^n} tilde.equiv k^n, wide L = {(A,0) : A in GLover(n,k)} tilde.equiv GLover(n,k).
$
That $L$ is a subgroup of $Affnk$ is clear. To prove that $Affnk = T times.r L$ we check three conditions.

- $T$ is a normal subgroup. Indeed, for all $A in GLover(n,k)$ and $v,w in k^n$ we have
  $
    (A,w) dot (I_n, v) dot (A^(-1),-A^(-1)w) 
    =  (A,A v + w) dot (A^(-1),-A^(-1)w) 
    \ = (A A^(-1), -A A^(-1)w + A v + w) 
    = (I_n, A v) in T.
  $

- The intersection $T inter L = {(I_n, 0)}$ is trivial.

- Every element $(A,v)$ can be decomposed uniquely as $(I_n, v) dot (A,0) =(A,v) $.  

Thus, $Affnk = T times.r L tilde.equiv k^n times.r GLover(n,k)$, with $GLover(n,k)$ acting on $k^n$ by matrix multiplication. 

Moreover, we can clearly see that for a group homomorphism $h: GLover(n,k) arrow Aut(k^n)$ defined by $h(A)(v) = A v$ it holds that
$ (A_1, v_1) dot (A_2, v_2) = (A_1 A_2, A_1 v_2 + v_1) = (A_1 A_2, h(A_1)(v_2) + v_1) $
and so $Affnk tilde.equiv k^n times.r_h GLover(n,k)$.


== Solution of (3)

Any element $(A,v) in Affnk$ can be equivalently expressed as a matrix 
$
  cal(A)_(A,v) 
  = mat(
    1,0,0,dots.c,0; 
    v_1, a_11, a_12,dots.c,a_(1n);
    v_2, a_21, a_22,dots.c,a_(2n);
    dots.v,dots.v,dots.v,dots.down,dots.v;
    v_n, a_(n 1), a_(n 2),dots.c,a_(n n);
  ) 
  = mat(1,0; v^T, A)
$
whose action on $x in Ank(n,k)$ satisfies
$
  cal(A)_(A,v) vec(x_0, x_1, x_2, dots.v, x_n) 
  = vec(
    x_0, 
    sum_(i=1)^n a_(1 i)x_i + v_1x_0, 
    sum_(i=1)^n a_(2 i)x_i + v_2x_0, 
    dots.v, 
    sum_(i=1)^n a_(n i)x_i + v_n x_0) 
    = A x + v
    = (A,v)(x).
$
Observe that $det (cal(A)_(A,v)) = det(A) eq.not 0$, hence $cal(A)_(A,v) in GLover(n+1,k)$. Similarly as before, let $[cal(A)_(A,v)] in PGLover(n+1,k)$ be the equivalence class under scalar multiplication which satisfies 
$
  [cal(A)_(A,v)] [x_0: dots:x_n] = [x_0 : sum_(i=1)^n a_(1 i)x_i + v_1x_0: sum_(i=1)^n a_(2 i)x_i + v_2x_0 : dots: sum_(i=1)^n a_(n i)x_i + v_n x_0]. 
$
When $x_0=1$ we have the following equality:
$
  [cal(A)_(A,v)] [x_1: dots:x_n] 
  = [1 : sum_(i=1)^n a_(1 i)x_i + v_1: dots: sum_(i=1)^n a_(n i)x_i + v_n] \ 
  = phi((sum_(i=1)^n a_(1 i)x_i + v_1, dots, sum_(i=1)^n a_(n i)x_i + v_n)) = phi(A x+v).
$

Next, consider a map $rho: Affnk arrow PGLover(n+1,k)$ given by $(A,v) mapsto [mat(1,0; v^T, A)]$. Because 
$
  rho((A,v) dot (B,w) ) 
  = rho(A B, A w +v) 
  = [mat(1,0; (A w +v)^T, A B)] \
  = [mat(1,0;v^T, A) mat(1,0;w^T , B)]
  = [mat(1,0;v^T, A)] [mat(1,0;w^T , B)] = rho((A,v)) rho((B,w)),
$
it follows that $rho$ is a homomorphism and so $"Im"rho$ is a subgroup of $PGLover(n+1,k)$.




== Solution of (4)


Let $psi : Ank(2,k) arrow Ank(2,k)$ be given by $(a,b) arrow.bar (a + f(b),b)$.  
Consider a map  $Psi ((a,b)) = (a - f(b),b)$. Then,
$ psi compose Psi (a,b) = psi (a - f(b),b) = (a - f(b) + f(b),b) = (a,b) = dots = Psi compose psi (a,b). $
Therefore, $Psi = psi^(-1)$ and so  $psi in Aut(Ank(2,k))$  for every $f in k[x]$.


Now, suppose that $psi$ is an affine transformation, that is,
$ psi ((a,b)) = mat(u, y; w,z) vec(a,b) + vec(c, d)=mat( a u  + b y + c; a w + b z + d), $
for some $u,y,w,z,c,d in k$.
Then, 
$
  a u  + b y + c = a + f(b), wide  a w + b z + d = b,
$
which implies that
$
  M= mat(1,y;0,1), quad v=vec(c,0), quad f(x) = y x + c.
$
Hence, if $psi$ is an affine transformation, then $deg f <= 1$. 
For the converse, if $f(x) = y x + c$, then $psi ((a,b)) = (a + y x + c, b)$, which is clearly affine with matrix $mat(1,v;0,1)$ and translation $vec(c,0)$.
Therefore, $psi$ is an affine transformation iff $deg f <= 1$.   

