FROM golang:1.26-alpine AS builder
WORKDIR /app


COPY restapi/go.mod restapi/go.sum .
RUN go mod download

COPY storage/go.mod storage/go.sum .
RUN go mod download

COPY . .

RUN --mount=type=cache,target=/root/.cache/go-build \
go build -o server restapi 

FROM alpine:3.24
RUN apk add --no-cache ca-certificates

WORKDIR /app

COPY --from=builder /app/server /app/server
COPY --from=builder /app/restapi/static /app/static

EXPOSE 8080
CMD ["./server"]
